### PR TITLE
[WIP] Support deserializing enums into Value

### PR DESCRIPTION
**Pull request by jrmuizel**
This is still pretty messy and I'm not sure if the approach
is a good one but it does seem to work.

### CODE REVIEW

**Comment by jrmuizel** [comment]
The Ron grammar is ambiguous in that case so it's not clear what should be done.

**Comment by torkleyy** [comment]
Oh sorry, this PR got forgotten.

**Comment by torkleyy** [comment]
Oh, this is still WIP. Are you still interested in this PR?

**Comment by torkleyy** [comment]
Closing due to inactivity. Feel free to re-open.

**Pull request closed without merging**
