### PR TITLE
Release 0.6 preparations

### PR DESCRIPTION
**Pull request by kvark**

### CODE REVIEW

**Comment by bpfoley** [comment]
Looks good to me. I went back over the changelog, and I've noticed that #182 and #173 are API breaks, so I wonder should they be moved to the Changes section.

**Comment by CAD97** [comment]
👍

**Comment by kvark** [comment]
bors r=bpfoley,CAD97

No strong opinion about moving those sections in the changelog, we can follow-up :)

**Comment by kvark** [comment]
Bors is unable to wait for tests for some reason:
> Status: Clippy: stable (Succeeded) Format: stable (Succeeded) Tests (Running)

Not sure why...

**Comment by CAD97** [comment]
I'll take another look at bors later today, see if I can fix that.

**Pull request merged**
