### PR TITLE
Use conventional module layout

### LINKED ISSUE #183: Unified Error type
Would it make sense to follow the pattern introduced by other `serde` libraries of exposing a top-level Error type that unifies the error types possible within the crate?
Some references:
[JSON](https://docs.serde.rs/serde_json/struct.Error.html)
[XML](https://docs.rs/serde-xml-rs/0.3.1/serde_xml_rs/struct.Error.html)
[YAML](https://docs.serde.rs/serde_yaml/struct.Error.html)
[bincode](https://docs.rs/bincode/1.1.4/bincode/type.Error.html)

If people think this is a desirable feature I'd like to submit a PR

### LINKED ISSUE #220: ron (the crate) should follow serde data format conventions
[Serde data format conventions](https://serde.rs/conventions.html) are basically summed up by the following lib.rs skeleton:

```rust
mod de;
mod error;
mod ser;

pub use de::{from_str, Deserializer};
pub use error::{Error, Result};
pub use ser::{to_string, Serializer};
```

### LINKED ISSUE #221: Display::fmt for de::Error is infinitely recursive
Caused by #208.

```diff
  impl fmt::Display for Error {
      fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
          match *self {
              Error::IoError(ref s) => write!(f, "{}", s),
              Error::Message(ref s) => write!(f, "{}", s),
-             Error::Parser(_, pos) => write!(f, "{}: {}", pos, self.description()),
+             Error::Parser(_, pos) => write!(f, "{}: {}", pos, self),
          }
      }
  }
```

### PR DESCRIPTION
**Pull request by CAD97**
This includes unifying ser::Error and de::Error.

Closes #183, closes #220, closes #221.

### CODE REVIEW

**Comment by kvark** [comment]
looks like we are failing - https://travis-ci.org/github/ron-rs/ron/builds/682117741
would be nice to move to GH actions...

**Comment by CAD97** [comment]
I did test this.

I'm going to [blame rust-analyzer](https://github.com/rust-analyzer/rust-analyzer/issues/4255) for the fact that this doesn't pass all of the tests yet 🙃

**Comment by CAD97** [comment]
Fixed the unfixed test fallout.

**Comment by kvark** [comment]
Great, thank you!

**Comment by Veetaha** [comment]
Hey guys, I suggest you to include this breaking change to the CHANGELOG.md, because old code that referred to `ron::de::Error` and `ron::ser::Error` types doesn't work anymore. One strange thing is that there is a path to new unified error via `ron::de::Error` I guess you've forgotten to remove `pub use` from there?

**Pull request merged**
