### PR TITLE
Replace Travis with GHA

### LINKED ISSUE #213: Move from Travis to GH actions
Travis (.org specifically) has been having a hard time lately.

### PR DESCRIPTION
**Pull request by CAD97**
As [mentioned here](https://github.com/ron-rs/ron/pull/222#issuecomment-622598923). Closes #213

### CODE REVIEW

**Comment by CAD97** [comment]
(*waves hand in a Jedi manner* you did not see that typo)

**Comment by CAD97** [comment]
Example workflow ruN: https://github.com/cad97/ron/actions/runs/93499721

**Comment by kvark** [comment]
Where is the typo? :)

**Comment by CAD97** [comment]
The typo is gone, force pushed to smithereens (pun not intended)

**Pull request merged**
