### PR TITLE
Be more permissive wrt whitespace

### PR DESCRIPTION
**Pull request by torkleyy**

### CODE REVIEW

**Comment by torkleyy** [comment]
Should we also allow `(  )` for units?

**Comment by Xaeroxe** [comment]
@torkleyy [Yes, it's valid syntax in Rust](https://play.rust-lang.org/?gist=624f9dce3de565536fc225f4bb3953f0&version=stable)

**Comment by torkleyy** [comment]
I know.

**Comment by kvark** [comment]
Thank you!
bors r+

**Pull request merged**
