### PR TITLE
Reexport `Value` at  root

### PR DESCRIPTION
**Pull request by matklad**
Hi! As a client of `ron`, I'd love to be able to use `ron::Value` :0)

### CODE REVIEW

**Comment by kvark** [comment]
Thank you!
I think we should hide `value` module then in the next breaking change.
bors r+

**Comment by torkleyy** [comment]
Thanks @matklad! Seems bors is stuck?

**Comment by torkleyy** [comment]
Just took a look at the log, it crashed: https://app.bors.tech/repositories/865/log

**Pull request merged**
