### PR TITLE
Add a test

### PR DESCRIPTION
**Pull request by suhr**
Tests are important. So I decided to add a new one.  Unlike other tests, it's small (almost cute) and easy to understand.

The test obviously doesn't pass because ron is broken.

### CODE REVIEW

**Comment by torkleyy** [comment]
I don't think it's RON that is broken. Fixed size arrays are handled like tuples in serde.

**Comment by torkleyy** [comment]
https://github.com/serde-rs/serde/issues/989

**Comment by suhr** [comment]
I see. Is this an intended behaviour that should be documented?

**Comment by torkleyy** [comment]
It's not really something that's specific to RON, but I guess it's surprising. Documentation would be good, but where?

**Comment by torkleyy** [comment]
Closing due to inactivity.

**Pull request closed without merging**
