### PR TITLE
Fix #174

### LINKED ISSUE #174: Depth limit seems to be off by one
Currently, a depth limit of `1` means that nothing gets indented (same for `0`). That seems wrong, as the limit should be the (inclusive) maximum depth.

This can be fixed by changing the `pretty.indent < config.ident` to a `<=` check.

@kvark Do you agree this is a bug?

### PR DESCRIPTION
**Pull request by CAD97**
Disclaimer: untested; just applies the patch recommended by @torkleyy in #174.

Closes #174.

### CODE REVIEW

**Comment by CAD97** [comment]
Looks like there is a test of the current behavior. I don't actually have this branch locally (and am working on drafting a rewrite version anyway) so I'll let you grab that test.

**Comment by kvark** [comment]
Well, since you made a PR first, you ought to finish it by correcting the tests expectations :)

**Comment by CAD97** [comment]
Oh, alright, I'll pull out my `git stash` and fix this 😄

**Comment by kvark** [comment]
bors try

**Pull request merged**
